baseURL = 'https://2022.jln.bz'
languageCode = 'en-us'
title = 'José Luis Núñez'
theme = 'just-me'

disableKinds = ["taxonomy", "term", "RSS", "sitemap"]

ga_tracking_id = "UA-52910819-1"

[params]
  author = "José Luis Núñez"
  author_link = "https://joseluisnuñez.es"
